# colorize CMake output
# code adapted from stackoverflow: http://stackoverflow.com/a/19578320

macro(define_colors)
  if(WIN32)
  # has no effect on WIN32
  set(ColourReset "")
  set(ColourBold "")
  set(Red "")
  set(Green "")
  set(Yellow "")
  set(Blue "")
  set(Magenta "")
  set(Cyan "")
  set(White "")
  set(BoldRed "")
  set(BoldGreen "")
  set(BoldYellow "")
  set(BoldBlue "")
  set(BoldMagenta "")
  set(BoldCyan "")
  set(BoldWhite "")
else()
  string(ASCII 27 Esc)
  set(ColourReset "${ESC}[m")
  set(ColourBold "${ESC}[1m")
  set(Red "${ESC}[31m")
  set(Green "${ESC}[32m")
  set(Yellow "${ESC}[33m")
  set(Blue "${ESC}[34m")
  set(Magenta "${ESC}[35m")
  set(Cyan "${ESC}[36m")
  set(White "${ESC}[37m")
  set(BoldRed "${ESC}[1;31m")
  set(BoldGreen "${ESC}[1;32m")
  set(BoldYellow "${ESC}[1;33m")
  set(BoldBlue "${ESC}[1;34m")
  set(BoldMagenta "${ESC}[1;35m")
  set(BoldCyan "${ESC}[1;36m")
  set(BoldWhite "${ESC}[1;37m")
endif()
endmacro()
